
Neos:
  Flow:
    security:
      authentication:
        providers:
          GoogleOAuth2Provider:
            provider: Flowpack\OAuth2\Client\Google\Provider
            providerOptions:
              authorizationEndpointUri: 'https://accounts.google.com/o/oauth2/auth'
              redirectionEndpointUri: 'https://www.yoursite.com/authentication/authenticate'
              tokenEndpointUri: 'https://accounts.google.com/o/oauth2/token'
              tokenEndpointClassName: Flowpack\OAuth2\Client\Google\TokenEndpoint
              clientIdentifier: 123456youridentifier.apps.googleusercontent.com
              clientSecret: '-add-your-client-secret-here-'
              responseType: code
              scopes:
                - 'https://www.googleapis.com/auth/userinfo.email'
                - 'https://www.googleapis.com/auth/userinfo.profile'
              partyCreation: true
              display: popup
